### ISSUE TITLE
FC on application start (Android 11 - LineageOS 18.1)

### ISSUE THREAD

**Issue by voxitme** [KaeruCT/GLXY#5]
Here is the crashlog :

```
FATAL EXCEPTION: GLThread 11660

Process: com.kaeruct.glxy, PID: 17951
com.badlogic.gdx.utils.f0: Error reading file: data/uiskin.json
	at a.a.a.x.a.k.n.b(Unknown Source:30)
	at a.a.a.x.a.k.n.<init>(Unknown Source:87)
	at com.kaeruct.glxy.e.e.<init>(Unknown Source:22)
	at com.kaeruct.glxy.e.d.<init>(Unknown Source:0)
	at com.kaeruct.glxy.e.c.<init>(Unknown Source:0)
	at com.kaeruct.glxy.a.a(Unknown Source:59)
	at com.kaeruct.glxy.a.e(Unknown Source:20)
	at a.a.a.s.a.l.onSurfaceChanged(Unknown Source:28)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: com.badlogic.gdx.utils.f0: Error reading file: data/uiskin.json
	at com.badlogic.gdx.utils.o.a(Unknown Source:35)
	at a.a.a.x.a.k.n.b(Unknown Source:6)
	... 9 more
Caused by: com.badlogic.gdx.utils.f0: 
	at a.a.a.x.a.k.n$b.a(Unknown Source:31)
	at a.a.a.x.a.k.n$b.a(Unknown Source:0)
	at com.badlogic.gdx.utils.o.a(Unknown Source:124)
	at a.a.a.x.a.k.n$a.a(Unknown Source:27)
	at com.badlogic.gdx.utils.o.a(Unknown Source:10)
	... 10 more
Caused by: com.badlogic.gdx.utils.o0.e: Class not found: com.badlogic.gdx.graphics.g2d.BitmapFont
	at com.badlogic.gdx.utils.o0.b.a(Unknown Source:25)
	at a.a.a.x.a.k.n$b.a(Unknown Source:18)
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.graphics.g2d.BitmapFont
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at com.badlogic.gdx.utils.o0.b.a(Unknown Source:0)
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.graphics.g2d.BitmapFont
	... 19 more
```

**Comment by pserwylo** [comment]
This is due to proguard. It removes `BitmapFont` if it is only loaded at runtime using reflection. It wont apply on debug builds, only the release build.

I just disabled it in one of my games.Who knows how many other classes will get tripped up by this down the track? https://github.com/retrowars/retrowars/commit/e907da90ce7572bd3f3d0c85f5b68b985e633e00#diff-2ade5f890d469ec9a1cb3c81ec33cdfeaf61b5698056c75580942e7c9ad599c2

Alternatively you can add an exception just for bitmap font.

**Comment by pserwylo** [comment]
Nevermind, I can see youve addressed this already in `master`!

**Comment by ghost** [comment]
@KaeruCT well done! You snapped it! Thanks :)

**Comment by KaeruCT** [comment]
Thanks for the report and the stacktrace, and the suggested fix! Hopefully this is also useful to other people with the same issue in their games.

Since today, the fixed version is available on F-Droid!
